In [35]:
import pandas as pd
import json

In [36]:
df = pd.read_json("dataset.json").T
df.head(5)

post_id  \
1179055004553900032_twitter  1179055004553900032_twitter   
1179063826874032128_twitter  1179063826874032128_twitter   
1178793830532956161_twitter  1178793830532956161_twitter   
1179088797964763136_twitter  1179088797964763136_twitter   
1179085312976445440_twitter  1179085312976445440_twitter   

                                                                    annotators  \
1179055004553900032_twitter  [{'label': 'normal', 'annotator_id': 1, 'targe...   
1179063826874032128_twitter  [{'label': 'normal', 'annotator_id': 1, 'targe...   
1178793830532956161_twitter  [{'label': 'normal', 'annotator_id': 4, 'targe...   
1179088797964763136_twitter  [{'label': 'hatespeech', 'annotator_id': 1, 't...   
1179085312976445440_twitter  [{'label': 'hatespeech', 'annotator_id': 4, 't...   

                                                                    rationales  \
1179055004553900032_twitter                                                 []   
1179063826874032128_twitter                                                 []   
1178793830532956161_twitter                                                 []   
1179088797964763136_twitter  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1179085312976445440_twitter  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   

                                                                   post_tokens  
1179055004553900032_twitter  [i, dont, think, im, getting, my, baby, them, ...  
1179063826874032128_twitter  [we, cannot, continue, calling, ourselves, fem...  
1178793830532956161_twitter                [nawt, yall, niggers, ignoring, me]  
1179088797964763136_twitter  [<user>, i, am, bit, confused, coz, chinese, p...  
1179085312976445440_twitter  [this, bitch, in, whataburger, eating, a, burg...

In [37]:
f = open("dataset.json")

data = json.load(f)


In [52]:
m = 0
for i in data :
#     print(i)
    if(m <= 5):
#         print(data[i])
#         print(data[i]['annotators'])
        for j in data[i]['annotators']:
            print(j['target'])
        
    m+=1

['None']
['None']
['None']
['None']
['None']
['None']
['African']
['None']
['African']
['Asian']
['Asian']
['Asian']
['Caucasian', 'Women']
['Women', 'Caucasian']
['Women', 'Caucasian']
['Jewish']
['Jewish']
['Jewish']


In [43]:
m = 0
final = []
for i in data :
#     print(i)
#     if(m <= 5):
    l = data[i]['post_tokens']
    st = ''
    for i in l:
        st += i
        st += ' '
#     data[i]['post_tokens'] = st
#     print(st)
    final.append(st)
#     print("---------------------------------------------------")

# print(data)
#     else:
#         break
#     m+=1
print(final)

['i dont think im getting my baby them white 9 he has two white j and nikes not even touched ', 'we cannot continue calling ourselves feminists if the rights of all womxn arent addressed yes to a sexual offences public list but will a trans lesbian bisexual and queer womxn be able to enter their information on the reporting sheet gender forum ', 'nawt yall niggers ignoring me ', '<user> i am bit confused coz chinese ppl can not access twitter thn how this ching chong using it i think he pakistani 🤔 🤔 🤔 ', 'this bitch in whataburger eating a burger with no top bun and holding it palm up i hate white bitches ', 'laura loomer raped me while screaming at me in her disgusting kike language and said we must exterminate the goyim laura loomer loomergate ', 'and this is why i end up with nigger trainee doctors who can not speak properly lack basic knowledge of biology it truly scary if the public only knew ', 'nogs jews and dykes how enriching ', 'guilty until proven innocent unless you are a 

In [44]:
ds = pd.DataFrame(final, columns=['Tokenized Strings'])

In [53]:
ds.head(6)

Tokenized Strings
0  i dont think im getting my baby them white 9 h...
1  we cannot continue calling ourselves feminists...
2                     nawt yall niggers ignoring me 
3  <user> i am bit confused coz chinese ppl can n...
4  this bitch in whataburger eating a burger with...
5  laura loomer raped me while screaming at me in...

In [47]:
ds.to_csv('string_tokenize.csv')

In [54]:
varun = pd.read_csv('Updated_Ultimate.csv')

In [55]:
varun.head(5)

Unnamed: 0                      post_id  \
0           0  1179055004553900032_twitter   
1           1  1179063826874032128_twitter   
2           2  1178793830532956161_twitter   
3           3  1179088797964763136_twitter   
4           4  1179085312976445440_twitter   

                                                text  annotatorid1  \
0  ['i', 'dont', 'think', 'im', 'getting', 'my', ...             1   
1  ['we', 'cannot', 'continue', 'calling', 'ourse...             1   
2      ['nawt', 'yall', 'niggers', 'ignoring', 'me']             4   
3  ['<user>', 'i', 'am', 'bit', 'confused', 'coz'...             1   
4  ['this', 'bitch', 'in', 'whataburger', 'eating...             4   

                  target1      label1  annotatorid2                 target2  \
0                ['None']      normal             2                ['None']   
1                ['None']      normal             2                ['None']   
2             ['African']      normal             2                ['None']   
3               ['Asian']  hatespeech             4               ['Asian']   
4  ['Caucasian', 'Women']  hatespeech             2  ['Women', 'Caucasian']   

       label2  annotatorid3                 target3      label3  \
0      normal             3                ['None']      normal   
1      normal             3                ['None']      normal   
2      normal             3             ['African']  hatespeech   
3   offensive             3               ['Asian']  hatespeech   
4  hatespeech             3  ['Women', 'Caucasian']   offensive   

                                          rationales final_label  \
0                                                 []   non-toxic   
1                                                 []   non-toxic   
2                                                 []   non-toxic   
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   
4  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   

  ultimate_label         ultimate_target  
0         normal                      []  
1         normal                      []  
2         normal             ['African']  
3     hatespeech               ['Asian']  
4     hatespeech  ['Women', 'Caucasian']

In [56]:
varun['tweets'] = ds

In [57]:
varun.head(5)

Unnamed: 0                      post_id  \
0           0  1179055004553900032_twitter   
1           1  1179063826874032128_twitter   
2           2  1178793830532956161_twitter   
3           3  1179088797964763136_twitter   
4           4  1179085312976445440_twitter   

                                                text  annotatorid1  \
0  ['i', 'dont', 'think', 'im', 'getting', 'my', ...             1   
1  ['we', 'cannot', 'continue', 'calling', 'ourse...             1   
2      ['nawt', 'yall', 'niggers', 'ignoring', 'me']             4   
3  ['<user>', 'i', 'am', 'bit', 'confused', 'coz'...             1   
4  ['this', 'bitch', 'in', 'whataburger', 'eating...             4   

                  target1      label1  annotatorid2                 target2  \
0                ['None']      normal             2                ['None']   
1                ['None']      normal             2                ['None']   
2             ['African']      normal             2                ['None']   
3               ['Asian']  hatespeech             4               ['Asian']   
4  ['Caucasian', 'Women']  hatespeech             2  ['Women', 'Caucasian']   

       label2  annotatorid3                 target3      label3  \
0      normal             3                ['None']      normal   
1      normal             3                ['None']      normal   
2      normal             3             ['African']  hatespeech   
3   offensive             3               ['Asian']  hatespeech   
4  hatespeech             3  ['Women', 'Caucasian']   offensive   

                                          rationales final_label  \
0                                                 []   non-toxic   
1                                                 []   non-toxic   
2                                                 []   non-toxic   
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   
4  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   

  ultimate_label         ultimate_target  \
0         normal                      []   
1         normal                      []   
2         normal             ['African']   
3     hatespeech               ['Asian']   
4     hatespeech  ['Women', 'Caucasian']   

                                              tweets  
0  i dont think im getting my baby them white 9 h...  
1  we cannot continue calling ourselves feminists...  
2                     nawt yall niggers ignoring me   
3  <user> i am bit confused coz chinese ppl can n...  
4  this bitch in whataburger eating a burger with...

In [59]:
varun.drop(columns=['Unnamed: 0','post_id'], inplace=True)

In [60]:
varun.head(5)

text  annotatorid1  \
0  ['i', 'dont', 'think', 'im', 'getting', 'my', ...             1   
1  ['we', 'cannot', 'continue', 'calling', 'ourse...             1   
2      ['nawt', 'yall', 'niggers', 'ignoring', 'me']             4   
3  ['<user>', 'i', 'am', 'bit', 'confused', 'coz'...             1   
4  ['this', 'bitch', 'in', 'whataburger', 'eating...             4   

                  target1      label1  annotatorid2                 target2  \
0                ['None']      normal             2                ['None']   
1                ['None']      normal             2                ['None']   
2             ['African']      normal             2                ['None']   
3               ['Asian']  hatespeech             4               ['Asian']   
4  ['Caucasian', 'Women']  hatespeech             2  ['Women', 'Caucasian']   

       label2  annotatorid3                 target3      label3  \
0      normal             3                ['None']      normal   
1      normal             3                ['None']      normal   
2      normal             3             ['African']  hatespeech   
3   offensive             3               ['Asian']  hatespeech   
4  hatespeech             3  ['Women', 'Caucasian']   offensive   

                                          rationales final_label  \
0                                                 []   non-toxic   
1                                                 []   non-toxic   
2                                                 []   non-toxic   
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   
4  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...       toxic   

  ultimate_label         ultimate_target  \
0         normal                      []   
1         normal                      []   
2         normal             ['African']   
3     hatespeech               ['Asian']   
4     hatespeech  ['Women', 'Caucasian']   

                                              tweets  
0  i dont think im getting my baby them white 9 h...  
1  we cannot continue calling ourselves feminists...  
2                     nawt yall niggers ignoring me   
3  <user> i am bit confused coz chinese ppl can n...  
4  this bitch in whataburger eating a burger with...

In [62]:
varun.to_csv('Updated_Dataset_4.csv')

In [2]:
!wget --no-check-certificate \
      "https://storage.googleapis.com/kaggle-datasets/30764/39238/Sarcasm_Headlines_Dataset.json.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1561457285&Signature=iF0OFX3Y7%2FsA%2Frg2BhTIlg%2FfAu%2BsxT4cQnOAI%2BthZFO2iltMdBQop0TBuE1QRrN4n8J6jBi235F81nf6CJ%2FFkx7Fx3mc4o2imDoRIK%2FPGC6Go4B8pyf9W3McsglpUVfkWRO8RX3zeKUZmbUkd9aP0WoMbrYo2kF0Fw5FaOBjjWnfJZjk3UPqME4U7b2KB08e%2BQknBMBLFkOE65TtZEHWa056gI2JoE37riXx0G6qjyypiPTmjePahOUE4EtPbDRUp2vukU%2FHEp%2Bh%2BNI9yx%2FruiTKufvD%2FdhMO87AjW3esGFwr41fGNlKrFihOcPSzi0%2FiyEAAH%2F8My7X43G777Vijw%3D%3D"\
      -O "sarcasm.zip"


--2021-04-05 20:13:56--  https://storage.googleapis.com/kaggle-datasets/30764/39238/Sarcasm_Headlines_Dataset.json.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1561457285&Signature=iF0OFX3Y7%2FsA%2Frg2BhTIlg%2FfAu%2BsxT4cQnOAI%2BthZFO2iltMdBQop0TBuE1QRrN4n8J6jBi235F81nf6CJ%2FFkx7Fx3mc4o2imDoRIK%2FPGC6Go4B8pyf9W3McsglpUVfkWRO8RX3zeKUZmbUkd9aP0WoMbrYo2kF0Fw5FaOBjjWnfJZjk3UPqME4U7b2KB08e%2BQknBMBLFkOE65TtZEHWa056gI2JoE37riXx0G6qjyypiPTmjePahOUE4EtPbDRUp2vukU%2FHEp%2Bh%2BNI9yx%2FruiTKufvD%2FdhMO87AjW3esGFwr41fGNlKrFihOcPSzi0%2FiyEAAH%2F8My7X43G777Vijw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 2404:6800:4007:82a::2010, 2404:6800:4007:80c::2010, 2404:6800:4007:80b::2010, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4007:82a::2010|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2021-04-05 20:13:56 ERROR 400: Bad Request.



In [3]:
!wget --no-check-certificate \
      "https://storage.googleapis.com/kaggle-datasets/30764/39238/Sarcasm_Headlines_Dataset.json.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1561457285&Signature=iF0OFX3Y7%2FsA%2Frg2BhTIlg%2FfAu%2BsxT4cQnOAI%2BthZFO2iltMdBQop0TBuE1QRrN4n8J6jBi235F81nf6CJ%2FFkx7Fx3mc4o2imDoRIK%2FPGC6Go4B8pyf9W3McsglpUVfkWRO8RX3zeKUZmbUkd9aP0WoMbrYo2kF0Fw5FaOBjjWnfJZjk3UPqME4U7b2KB08e%2BQknBMBLFkOE65TtZEHWa056gI2JoE37riXx0G6qjyypiPTmjePahOUE4EtPbDRUp2vukU%2FHEp%2Bh%2BNI9yx%2FruiTKufvD%2FdhMO87AjW3esGFwr41fGNlKrFihOcPSzi0%2FiyEAAH%2F8My7X43G777Vijw%3D%3D"\
      -O "/tmp/sarcasm.zip"

--2021-04-05 20:14:36--  https://storage.googleapis.com/kaggle-datasets/30764/39238/Sarcasm_Headlines_Dataset.json.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1561457285&Signature=iF0OFX3Y7%2FsA%2Frg2BhTIlg%2FfAu%2BsxT4cQnOAI%2BthZFO2iltMdBQop0TBuE1QRrN4n8J6jBi235F81nf6CJ%2FFkx7Fx3mc4o2imDoRIK%2FPGC6Go4B8pyf9W3McsglpUVfkWRO8RX3zeKUZmbUkd9aP0WoMbrYo2kF0Fw5FaOBjjWnfJZjk3UPqME4U7b2KB08e%2BQknBMBLFkOE65TtZEHWa056gI2JoE37riXx0G6qjyypiPTmjePahOUE4EtPbDRUp2vukU%2FHEp%2Bh%2BNI9yx%2FruiTKufvD%2FdhMO87AjW3esGFwr41fGNlKrFihOcPSzi0%2FiyEAAH%2F8My7X43G777Vijw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 2404:6800:4007:82a::2010, 2404:6800:4007:80c::2010, 2404:6800:4007:80b::2010, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4007:82a::2010|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2021-04-05 20:14:37 ERROR 400: Bad Request.



In [4]:
import os
import zipfile

local_zip='/tmp/sarcasm.zip'
zip_ref=zipfile.ZipFile(local_zip,'r')
zip_ref.extractall('/tmp/sarcasm')
zip_ref.close()

BadZipFile: File is not a zip file

In [157]:
import pandas as pd


In [158]:
df = pd.read_csv("FinalDataset.csv")

In [159]:
df.head(500)

Unnamed: 0                                             tweets       class
0             0   well that the primary reason but it mostly su...  hatespeech
1             1                  hate feeling like this not fair       sarcasm
2             2  that awkward moment when you have to make up a...     sarcasm
3             3  i do not care what anyone does on here to make...   offensive
4             4  you all i lost one of those little white bitch...      normal
..          ...                                                ...         ...
495         495  the blm leadership have been out disrupting lg...  hatespeech
496         496  hybrid long runs  what cruel person invented y...     sarcasm
497         497  your prime minister is too busy lashing at rus...  hatespeech
498         498  im sorry i hurt your feelings when i called yo...     sarcasm
499         499  france is finished might as well just ignore t...  hatespeech

[500 rows x 3 columns]

In [160]:
stopwords=[ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]


In [161]:
def remove_stopwords(sentence):
    for word in stopwords:
        token=' '+word+' '
        sentence=sentence.replace(token,' ')
        sentence=sentence.replace('  ',' ')
    return sentence

In [162]:
df.drop(columns =['Unnamed: 0'], inplace=True)

In [163]:
# labels = []
# text = []

# text = df['tweets']
# labels = df['class']


df.head(5)

tweets       class
0   well that the primary reason but it mostly su...  hatespeech
1                  hate feeling like this not fair       sarcasm
2  that awkward moment when you have to make up a...     sarcasm
3  i do not care what anyone does on here to make...   offensive
4  you all i lost one of those little white bitch...      normal

In [164]:
df['class'].value_counts()

sarcasm       10307
normal         7793
hatespeech     6850
offensive      5474
Name: class, dtype: int64

In [165]:
from sklearn.model_selection import train_test_split

X = df.drop('class',axis=1)
y = df['class']

for i in range(len(y)):
    if y[i]=='sarcasm':
        y[i]=0
    elif y[i] == 'normal':
        y[i]=1
    elif y[i] == 'hatespeech':
        y[i]=2
    else:
        y[i]=3


In [166]:
y.value_counts()

0    10307
1     7793
2     6850
3     5474
Name: class, dtype: int64

In [167]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import SpatialDropout1D

In [168]:
tf.__version__

'2.2.0'

In [169]:
voc_size=5000

In [170]:
messages=X.copy()

In [171]:
messages['tweets'][1]

'hate feeling like this not fair  '

In [172]:
corpus = []
for i in messages['tweets']:
    corpus.append(i)

In [173]:
corpus

[' well that the primary reason but it mostly supported by the fact that niggers never keep the same energy all words no action ',
 'hate feeling like this not fair  ',
 'that awkward moment when you have to make up an excuse not to hang out with someone because youd rather chill at home   ',
 'i do not care what anyone does on here to make me look bad i am more interested in the truth than what some retard wants to say about me in case u have not noticed ',
 'you all i lost one of those little white bitches i cant find my left airpod it over ',
 'about to rip my contacts out and throw them on the floor  not today  ',
 'oprah is an affirmative action piece of shit fat ass nigger bitch ',
 ' if you can measure how well white families are doing it would be some shit like white percent blacks percent hispanic percent you should not be focused on whites doing better the problem is not white privilege it colored un privilege ',
 'is there anything doctors love more than wearing their lab co

In [174]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2837,
  3918,
  2654,
  845,
  1758,
  2582,
  500,
  2698,
  1711,
  1525,
  2654,
  2988,
  3918,
  941,
  931,
  4665,
  2654,
  3697,
  2160,
  425,
  1934,
  3561,
  1659],
 [2584, 1019, 4804, 2789, 2227, 2877],
 [3918,
  384,
  3340,
  4034,
  1265,
  4173,
  3085,
  1290,
  3539,
  3871,
  810,
  2227,
  3085,
  4583,
  4484,
  196,
  254,
  2188,
  2788,
  4050,
  2565,
  2836,
  3897],
 [666,
  4455,
  2227,
  4149,
  4483,
  3413,
  1655,
  1550,
  3972,
  3085,
  1290,
  4225,
  1779,
  2075,
  666,
  3840,
  1351,
  1116,
  4798,
  2654,
  27,
  1472,
  4483,
  3544,
  1415,
  1935,
  3085,
  1969,
  2672,
  4225,
  4798,
  713,
  4989,
  4173,
  2227,
  1524],
 [1265,
  425,
  666,
  3450,
  669,
  348,
  3921,
  1395,
  3191,
  736,
  666,
  4489,
  103,
  2143,
  4856,
  2105,
  500,
  493],
 [2672,
  3085,
  2302,
  2143,
  998,
  4484,
  3428,
  374,
  3488,
  1550,
  2654,
  387,
  2227,
  4760],
 [1838, 1835, 3871, 2646, 1659, 2433, 348, 3227, 4044, 4947, 552, 215]

In [183]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[ 845 1758 2582 ... 1934 3561 1659]
 [   0    0    0 ... 2789 2227 2877]
 [4034 1265 4173 ... 2565 2836 3897]
 ...
 [   0    0    0 ... 2026  388 2227]
 [   0    0    0 ... 2735 3381 3907]
 [   0    0    0 ... 2644 2654 1906]]


In [184]:
## Creating model
# embedding_vector_features=40
# model1=Sequential()
# model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model1.add(Bidirectional(LSTM(100)))
# model1.add(Dropout(0.3))
# model1.add(Dense(1,activation='sigmoid'))

# model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model1.summary())
# # max_len = 60
# model = Sequential()
# model.add(Input(shape=(max_len,)))
# model.add(Embedding(voc_size,100,weights=[embedding_vector_features],input_length=max_len))
# model.add(Bidirectional (LSTM (100,return_sequences=True,dropout=0.50),merge_mode='concat'))
# model.add(TimeDistributed(Dense(100,activation='relu')))
# model.add(Flatten())
# model.add(Dense(100,activation='relu'))
# model.add(Dense(3,activation='softmax'))
# # model = Model(input,output)
# model.compile(loss='sparse_categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

# model.summary()

model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
# model.add(SpatialDropout1D(0.2))
model.add(Bidirectional(LSTM(100, dropout=0.2, recurrent_dropout=0.2)))
model.add(Dropout(0.3))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 5
batch_size = 64

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_15 (Embedding)     (None, 20, 40)            200000    
_________________________________________________________________
bidirectional_8 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_6 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 4)                 804       
Total params: 313,604
Trainable params: 313,604
Non-trainable params: 0
_________________________________________________________________
None


In [185]:
len(embedded_docs),y.shape, X_final.shape

(30424, (30424,), (30424, 20))

In [186]:
X_final[1]

array([2584, 1019, 4804, 2789, 2227, 2877,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [187]:
import numpy as np
X_final=np.asarray(embedded_docs).astype(np.int)
y_final=np.asarray(y).astype(np.int)

In [188]:
X_final.shape,y_final.shape

((30424, 20), (30424,))

In [189]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [190]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=4,batch_size=64)
# from keras.callbacks import ModelCheckpoint, EarlyStopping
# history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/4
381/381 [==============================] - 15s 39ms/step - loss: -1271.9771 - accuracy: 0.5519 - val_loss: -1081.8594 - val_accuracy: 0.4871
Epoch 2/4
381/381 [==============================] - 14s 36ms/step - loss: -1326.5706 - accuracy: 0.5546 - val_loss: -1123.8145 - val_accuracy: 0.5114
Epoch 3/4
381/381 [==============================] - 14s 37ms/step - loss: -1376.6429 - accuracy: 0.5605 - val_loss: -1161.4562 - val_accuracy: 0.5093
Epoch 4/4
381/381 [==============================] - 14s 36ms/step - loss: -1423.1538 - accuracy: 0.5629 - val_loss: -1186.3184 - val_accuracy: 0.5067


AttributeError: 'numpy.ndarray' object has no attribute 'type'